version: "3.1"
services:
  yakovlev_io_client:
    container_name: YakovlevIOClient
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    env_file: ./client/.env
