version: "3.9"
services:
  yakovlev-io-client:
    container_name: YakovlevIO
      build:
        context: ./client
        dockerfile: Dockerfile
    ports:
      - "80:3000"
    env_file: ./client/.env